DROP TABLE IF EXISTS heros;
CREATE TABLE heros (
    id int(11) NOT NULL,
    name VARCHAR(255) NOT NULL,
    hp_max FLOAT NULL DEFAULT NULL,
    hp_growth FLOAT NULL DEFAULT NULL,
    hp_start FLOAT NULL DEFAULT NULL,
    mp_max FLOAT NULL DEFAULT NULL,
    mp_growth FLOAT NULL DEFAULT NULL,
    mp_start FLOAT NULL DEFAULT NULL,
    attack_max FLOAT NULL DEFAULT NULL,
    attack_growth FLOAT NULL DEFAULT NULL,
    attack_start FLOAT NULL DEFAULT NULL,
    defense_max FLOAT NULL DEFAULT NULL,
    defense_growth FLOAT NULL DEFAULT NULL,
    defense_start FLOAT NULL DEFAULT NULL,
    hp_5s_max float NULL DEFAULT NULL,
    hp_5s_growth float NULL DEFAULT NULL,
    hp_5s_start float NULL DEFAULT NULL,
    mp_5s_max float NULL DEFAULT NULL,
    mp_5s_growth float NULL DEFAULT NULL,
    mp_5s_start float NULL DEFAULT NULL,
    attack_speed_max float NULL DEFAULT NULL,
    attack_range VARCHAR(255) NULL DEFAULT NULL,
    role_main VARCHAR(255) NULL DEFAULT NULL,
    role_assist VARCHAR(255) NULL DEFAULT NULL,
    birthdate DATE NULL DEFAULT NULL,
    PRIMARY KEY (id) USING BTREE
);